#!/bin/bash

# Quick Reference: Phase 3.1 Testing Commands

PROJECT_DIR="/Users/omkarjoshi/javaprojects/distributed-key-vault"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          Phase 3.1 - Testing Framework Quick Reference         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 COMMON COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  RUN FULL TEST SUITE (Recommended)"
echo "   cd $PROJECT_DIR"
echo "   ./run_test_suite.sh"
echo "   → Comprehensive tests + metrics + HTML report"
echo ""

echo "2️⃣  RUN PYTHON TEST SUITE"
echo "   python3 $PROJECT_DIR/test_phase_3_1.py"
echo "   → 7 scenarios with detailed output"
echo ""

echo "3️⃣  RUN INTERACTIVE FAILURE TESTS"
echo "   $PROJECT_DIR/test_failures.sh"
echo "   → Menu-driven failure scenarios"
echo "   → Requires manual node kill/restart"
echo ""

echo "4️⃣  ANALYZE SPECIFIC METRICS"
echo "   python3 $PROJECT_DIR/analyze_metrics.py <csv_file>"
echo "   python3 $PROJECT_DIR/analyze_metrics.py <csv_file> <output.json>"
echo ""

echo ""
echo "🔧 CLUSTER MANAGEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "START CLUSTER (clean)"
echo "   cd $PROJECT_DIR && rm -rf data/"
echo "   for port in 8080 8081 8082; do"
echo "     java -jar build/libs/distributed-key-vault-0.0.1-SNAPSHOT.jar \\"
echo "       --SERVER_PORT=\$port > /tmp/node_\$port.log 2>&1 &"
echo "   done"
echo ""

echo "STOP CLUSTER"
echo "   pkill -f 'SERVER_PORT'"
echo ""

echo "CHECK CLUSTER STATUS"
echo "   for port in 8080 8081 8082; do"
echo "     curl -s http://localhost:\$port/raft/state | jq '.'"
echo "   done"
echo ""

echo ""
echo "📊 USEFUL CURL COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Get node state"
echo "   curl -s http://localhost:8080/raft/state | jq '.'"
echo ""

echo "Write key-value"
echo "   curl -X PUT http://localhost:8080/vault/key \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"key\":\"username\",\"value\":\"alice\"}'"
echo ""

echo "Read key"
echo "   curl http://localhost:8080/vault/key/username"
echo ""

echo "Export metrics as CSV"
echo "   curl http://localhost:8080/metrics/export > metrics.csv"
echo ""

echo "Get metrics status"
echo "   curl http://localhost:8080/metrics/status | jq '.'"
echo ""

echo "Clear metrics"
echo "   curl -X DELETE http://localhost:8080/metrics/clear"
echo ""

echo ""
echo "📁 DIRECTORY STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PROJECT_DIR/"
echo "├── test_phase_3_1.py         ← Python test suite (7 scenarios)"
echo "├── test_failures.sh          ← Interactive failure scenarios"
echo "├── run_test_suite.sh         ← Full orchestration"
echo "├── analyze_metrics.py        ← Metrics analyzer"
echo "├── TESTING.md                ← Full documentation"
echo "├── test_reports/             ← Generated reports & metrics"
echo "│   └── phase_3_1_report_*/   ← Timestamped results"
echo "│       ├── index.html        ← HTML summary"
echo "│       └── metrics/          ← CSV exports & analysis"
echo "└── data/                     ← Node persistent state"
echo "    ├── node1/               ← Node 8080 state"
echo "    ├── node2/               ← Node 8081 state"
echo "    └── node3/               ← Node 8082 state"
echo ""

echo ""
echo "🔍 DIAGNOSTICS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Check server logs"
echo "   tail -f /tmp/node_8080.log"
echo "   tail -f /tmp/node_8081.log"
echo "   tail -f /tmp/node_8082.log"
echo ""

echo "Find leader"
echo "   for port in 8080 8081 8082; do"
echo "     role=\$(curl -s http://localhost:\$port/raft/state | grep -o '\"role\":\"[^\"]*\"' | cut -d'\"' -f4)"
echo "     echo \"Port \$port: \$role\""
echo "   done"
echo ""

echo ""
echo "📈 WORKFLOW FOR PAPER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Run healthy baseline"
echo "   ./run_test_suite.sh → Save metrics/baseline_healthy.csv"
echo ""
echo "2. Run failure scenarios (10 iterations each)"
echo "   ./test_failures.sh (Scenario 1: Leader Crash)"
echo "   ./test_failures.sh (Scenario 3: Rapid Writes)"
echo ""
echo "3. Analyze all runs"
echo "   for f in metrics_*.csv; do"
echo "     python3 analyze_metrics.py \$f >> analysis_summary.json"
echo "   done"
echo ""
echo "4. Generate paper figures"
echo "   → Election latency distribution"
echo "   → Term growth timeline"
echo "   → Leadership stability comparison"
echo ""

echo ""
echo "✅ TEST CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "□ Cluster running (3 nodes on 8080-8082)"
echo "□ Leader elected and responding"
echo "□ Follower rejecting writes (403)"
echo "□ Metrics being collected"
echo "□ CSV export working"
echo "□ Test reports generating"
echo ""

echo "For full documentation, see: $PROJECT_DIR/TESTING.md"
echo ""
